using Godot;

/// <summary>
/// A PhysicalBone3D Wrapper to handle active ragdoll. <br/>
/// Should be used in pair with a PHX_RagdollSim. They are generated by it.
/// </summary>
public class PHX_ActiveRagdollBone
{
    // Parent fetched by default
    private PhysicalBone3D _bone;
    // Bone parent fetched by default
    private PHX_ActiveRagdollSim _simulator;

    public PHX_ActiveRagdollBone(PhysicalBone3D bone, PHX_ActiveRagdollSim simulator) {
        _bone = bone;
        _simulator = simulator;    
    }

    public void Hit(Vector3 impulse, Vector3? from = null)
    {
        _simulator.StartSimulation();
        _bone.ApplyImpulse(impulse, from);
    }

    public void GlobalHit(Vector3 impulse, Vector3? from = null) =>
        _simulator.Hit(impulse, from);

    public void ApplyImpulse(Vector3 impulse, Vector3? position = null) =>
        _bone.ApplyImpulse(impulse, position);
}