// <auto-generated />
using System;
using Data.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260710213056_AddCreatedAtToScore")]
    partial class AddCreatedAtToScore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Map", b =>
                {
                    b.Property<string>("MapKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("MapKey");

                    b.ToTable("maps", (string)null);

                    b.HasData(
                        new
                        {
                            MapKey = "dust_pit"
                        });
                });

            modelBuilder.Entity("Data.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("MapKey")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MapKey");

                    b.HasIndex("PlayerId");

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Weapon", b =>
                {
                    b.Property<string>("WeaponKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("WeaponKey");

                    b.ToTable("weapons", (string)null);

                    b.HasData(
                        new
                        {
                            WeaponKey = "p3_w"
                        },
                        new
                        {
                            WeaponKey = "g0z_brt"
                        },
                        new
                        {
                            WeaponKey = "fists"
                        });
                });

            modelBuilder.Entity("Data.Entities.WeaponStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("Accuracy")
                        .HasColumnType("real");

                    b.Property<float?>("CriticalAccuracy")
                        .HasColumnType("real");

                    b.Property<float>("Damage")
                        .HasColumnType("real");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("WeaponKey")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ScoreId");

                    b.HasIndex("WeaponKey");

                    b.ToTable("weapon_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Score", b =>
                {
                    b.HasOne("Data.Entities.Map", "Map")
                        .WithMany("Scores")
                        .HasForeignKey("MapKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Player", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Data.Entities.WeaponStat", b =>
                {
                    b.HasOne("Data.Entities.Score", "Score")
                        .WithMany("WeaponStats")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Weapon", "Weapon")
                        .WithMany("WeaponStats")
                        .HasForeignKey("WeaponKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Score");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Data.Entities.Map", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Data.Entities.Player", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Data.Entities.Score", b =>
                {
                    b.Navigation("WeaponStats");
                });

            modelBuilder.Entity("Data.Entities.Weapon", b =>
                {
                    b.Navigation("WeaponStats");
                });
#pragma warning restore 612, 618
        }
    }
}
