// <auto-generated />
using System;
using Data.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260711113129_ApplySnakeCaseNaming")]
    partial class ApplySnakeCaseNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Map", b =>
                {
                    b.Property<string>("MapKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("map_key");

                    b.HasKey("MapKey")
                        .HasName("pk_maps");

                    b.ToTable("maps", (string)null);

                    b.HasData(
                        new
                        {
                            MapKey = "dust_pit"
                        });
                });

            modelBuilder.Entity("Data.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_players_username");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("MapKey")
                        .IsRequired()
                        .HasColumnType("character varying(64)")
                        .HasColumnName("map_key");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("TimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_ms");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_scores");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_scores_player_id");

                    b.HasIndex("MapKey", "Difficulty", "PlayerId", "Value")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_scores_leaderboard_lookup");

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Weapon", b =>
                {
                    b.Property<string>("WeaponKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("weapon_key");

                    b.HasKey("WeaponKey")
                        .HasName("pk_weapons");

                    b.ToTable("weapons", (string)null);

                    b.HasData(
                        new
                        {
                            WeaponKey = "p3_w"
                        },
                        new
                        {
                            WeaponKey = "g0z_brt"
                        },
                        new
                        {
                            WeaponKey = "fists"
                        });
                });

            modelBuilder.Entity("Data.Entities.WeaponStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("Accuracy")
                        .HasColumnType("real")
                        .HasColumnName("accuracy");

                    b.Property<float?>("CriticalAccuracy")
                        .HasColumnType("real")
                        .HasColumnName("critical_accuracy");

                    b.Property<float>("Damage")
                        .HasColumnType("real")
                        .HasColumnName("damage");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("score_id");

                    b.Property<string>("WeaponKey")
                        .IsRequired()
                        .HasColumnType("character varying(64)")
                        .HasColumnName("weapon_key");

                    b.HasKey("Id")
                        .HasName("pk_weapon_stats");

                    b.HasIndex("ScoreId")
                        .HasDatabaseName("ix_weapon_stats_score_id");

                    b.HasIndex("WeaponKey")
                        .HasDatabaseName("ix_weapon_stats_weapon_key");

                    b.ToTable("weapon_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Score", b =>
                {
                    b.HasOne("Data.Entities.Map", "Map")
                        .WithMany("Scores")
                        .HasForeignKey("MapKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scores_maps_map_key");

                    b.HasOne("Data.Entities.Player", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scores_players_player_id");

                    b.Navigation("Map");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Data.Entities.WeaponStat", b =>
                {
                    b.HasOne("Data.Entities.Score", "Score")
                        .WithMany("WeaponStats")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weapon_stats_scores_score_id");

                    b.HasOne("Data.Entities.Weapon", "Weapon")
                        .WithMany("WeaponStats")
                        .HasForeignKey("WeaponKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weapon_stats_weapons_weapon_key");

                    b.Navigation("Score");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Data.Entities.Map", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Data.Entities.Player", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Data.Entities.Score", b =>
                {
                    b.Navigation("WeaponStats");
                });

            modelBuilder.Entity("Data.Entities.Weapon", b =>
                {
                    b.Navigation("WeaponStats");
                });
#pragma warning restore 612, 618
        }
    }
}
